### ISSUE TITLE
failed to solve SDP 

### ISSUE THREAD

**Issue by wangjie212** [COPT-Public/COPT.jl#13]
When I try to solve an SDP with COPT 5.0.1, I get the following error:

_MathOptInterface.UnsupportedConstraint{MathOptInterface.VectorOfVariables, MathOptInterface.PositiveSemidefiniteConeTriangle}: `MathOptInterface.VectorOfVariables`-in-`MathOptInterface.PositiveSemidefiniteConeTriangle` constraint is not supported by the model._

I use JuMP v1.1.1.

**Comment by odow** [comment]
The JuMP API does not support PSD constraints yet.

**Comment by COPT-Public** [comment]
We are still adding SDP support.

**Comment by COPT-Public** [comment]
We finished our SDP support development. It should work now.
