### ISSUE TITLE
LP termination status 7 is not wrapped by COPT.jl

### ISSUE THREAD

**Issue by YangBo17** [COPT-Public/COPT.jl#17]
I use COPT.jl to solve a Polynomial optimization problem, however, there is a Error: LP termination status 7 is not wrapped by COPT.jl.

What is the meaning of this Error, and how to fix this problem?

**Comment by joachimdahl** [comment]
Can you provide a minimal example demonstrating the issue?

**Comment by lschork2** [comment]
Thank you for reporting the issue. This was a bug in the COPT Julia interface, which we have fixed now in version 1.0.7. You can update your installation to the latest version by running `import Pkg; Pkg.update("COPT");` from Julia.
