### ISSUE TITLE
VectorAffineFunction constraint of semidefinite programming is not supported

### ISSUE THREAD

**Issue by ivanightingale** [COPT-Public/COPT.jl#18]
Upon adding a constraint to my `model` I got the following error
```
ERROR: LoadError: Constraints of type MathOptInterface.VectorAffineFunction{Float64}-in-MathOptInterface.PositiveSemidefiniteConeSquare are not supported by the solver.
```
My constraint is something like `@constraint(model, Q in PSDCone())` where `Q` is affine in the variables.

Does COPT just not support this kind of constraint? That doesn't seem likely, because this is the class of constraints of the form $Ax+b$ which is pretty common.

**Comment by joachimdahl** [comment]
It is supposed to work as you outline.

First, please check that you use `COPT.ConeOptimizer` rather than `COPT.Optimizer`, see https://github.com/COPT-Public/COPT.jl#quick-check.

If the problem persists, can you provide a minimal working example to reproduce the issue?

**Comment by ivanightingale** [comment]
Yes, that works now. I should have read the documentation more carefully. Thank you!
