### ISSUE TITLE
Constraint Violation

### ISSUE THREAD

**Issue by YangBo17** [COPT-Public/COPT.jl#19]
I use COPT.jl to solve a SOS problem, which is transformed to be a SDP problem. However, I find that some inequality constraints are violated, I want to know whether constraint violation is allowed in COPT.jl?

**Comment by joachimdahl** [comment]
The COPT solution satisfies standard KKT optimality conditions to within the tolerance levels. All constraints and conic memberships must be satisfied.

How do you verify inequality constraints are violated, and by how much? 

If you can, please provide a minimal example to coptsupport@shanshu.ai. Then we will take a look at the model.
