### ISSUE TITLE
Support IIS (irreducible inconsistent subsystem)

### ISSUE THREAD

**Issue by mzy2240** [COPT-Public/COPT.jl#22]
Can we add the support for checking which constraints are conflicted? I heard the C interface and the python interface already support this feature.

**Comment by odow** [comment]
Docs: https://jump.dev/MathOptInterface.jl/dev/reference/models/#Conflict-Status

Gurobi implementation: https://github.com/jump-dev/Gurobi.jl/blob/555efdf64940812ac954519e34bdb77a1dc7ad53/src/MOI_wrapper/MOI_wrapper.jl#L3744-L3925

**Comment by joachimdahl** [comment]
This should be included with #23, so I am closing this.
