### ISSUE TITLE
Support start_value

### ISSUE THREAD

**Issue by mzy2240** [COPT-Public/COPT.jl#32]
it seems COPT supports setting up the start values for MIP: https://guide.coap.online/copt/en-doc/mipstart.html#mip-starts

**Comment by odow** [comment]
Does it not already? Do you have an example that is failing?

The code looks like it is in-place:

https://github.com/COPT-Public/COPT.jl/blob/aa20e4927f94ee91e0271444d80731ff92b6a400/src/MOI/MOI_wrapper.jl#L3489-L3514

https://github.com/COPT-Public/COPT.jl/blob/aa20e4927f94ee91e0271444d80731ff92b6a400/src/MOI/MOI_wrapper.jl#L2862-L2879

**Comment by mzy2240** [comment]
That’s surprising🙃 Thanks!
