### ISSUE TITLE
dual simplex from an infeasible solution

### ISSUE THREAD

**Issue by mzy2240** [COPT-Public/COPT.jl#34]
I have an iterative process to progressively add new constraints (or add to the objective function if converted into soft constraint) to a LP problem. I am just wondering if I can re-use the solution from the previous iteration as the starting point of the LP process. I think theoretically it should be supported by the dual simplex algorithm, am I right?

**Comment by joachimdahl** [comment]
If your question involves the use of COPT, then please refer to COPT support for how to achieve this.
