### ISSUE TITLE
Settings customization

### ISSUE THREAD

**Issue by Betristor** [COPT-Public/COPT.jl#36]
Is there a way to adjust settings for the COPT solver like time limit, cores it could use, and something more with attributes that could be set when specifying the optimizer? Gurobi.jl exports nearly all the attributes as APIs that could be customized by users, like:

```
    OPTIMIZER = optimizer_with_attributes(
        Gurobi.Optimizer,
        "OptimalityTol" => MyOptimalityTol,
        "FeasibilityTol" => MyFeasibilityTol,
        "Presolve" => MyPresolve,
        "AggFill" => MyAggFill,
        "PreDual" => MyPreDual,
        "TimeLimit" => MyTimeLimit,
        "BarIterLimit" => MyBarIterLimit,
        "MIPGap" => MyMIPGap,
        "Method" => MyMethod,
        "BarConvTol" => MyBarConvTol,
        "NumericFocus" => MyNumericFocus,
        "Crossover" => MyCrossover,
        "BarHomogeneous" => MyBarHomogeneous,
        "OutputFlag" => MyOutputFlag,
        "LogFile" => MyLogFile,
        "LogToConsole" => MyLogToConsole,
        "Threads" => MyThreads,
    )
```

**Comment by joachimdahl** [comment]
All parameters can be controlled from Julia.  I agree this could be made more visible.  

You need to look in MOI_wrapper.jl, where it's documented.

Here an example string copy-pasted from there:

> 
>     Optimizer(env::Union{Nothing, Env} = nothing)
> 
> Create a new Optimizer object.
> 
> You can share COPT `Env`s between models by passing an instance of `Env` as the
> first argument.
> 
> Set optimizer attributes using `MOI.RawOptimizerAttribute` or
> `JuMP.set_optimizer_atttribute`.
> 
> ## Example
> 
> ```julia
> using JuMP, COPT
> const env = COPT.Env()
> model = JuMP.Model(() -> COPT.Optimizer(env)
> set_optimizer_attribute(model, "LogToConsole", 0)
> ```
>

**Comment by Betristor** [comment]
Sure, I'd like to compile a list of all supported parameters and their corresponding names for convenience.
