### ISSUE TITLE
Consider adding CI

### ISSUE THREAD

**Issue by odow** [COPT-Public/COPT.jl#4]
We can test Gurobi on CI by installing the license from a secret environment variable:
https://github.com/jump-dev/Gurobi.jl/blob/e1a163acfa8aca98059bbef43c0aefe0f540591d/.github/workflows/ci.yml#L31-L34

This would only work if you can generate some uber-license that works regardless of the machines MAC address.

Would require https://github.com/COPT-Public/COPT.jl/issues/3

**Comment by lschork2** [comment]
Since version 4.0.5 COPT solves LP models up to size 10k-by-10k and other models up to 2k-by-2k without license (for non-commercial use). This seems to be enough for the tests from MathOptInterface.
