### ISSUE TITLE
What is the underlying API of COPT 32-bit or 64 bit

### ISSUE THREAD

**Issue by Betristor** [COPT-Public/COPT.jl#42]
Lately I have encountered a problem that Gurobi.jl will crush the machine when the number of variables exceeds 2147483647. I have some discussions with @odow, see [here](https://discourse.julialang.org/t/large-scale-model-using-gurobi-causes-machine-crushed/121988/6). The machine crushed because Gurobi.jl wraps 32-bit C API, leading to a limit of 2147483647 and my problem is oversized. I'm wondering if there is the same limit with COPT.jl.

**Comment by Betristor** [comment]
Ok, thanks. Same question as in the post, is there any plan to extend the limit?

**Comment by joachimdahl** [comment]
Maybe eventually, but I don't think we will change this in the short term.

**Comment by Betristor** [comment]
Thanks, now I do think it's necessary to reduce the problem size and I shall close this issue.
