### ISSUE TITLE
Creating versions

### ISSUE THREAD

**Issue by odow** [COPT-Public/COPT.jl#5]
* Julia maintains a list of supported packages here: https://github.com/JuliaRegistries/General
* If the package is in General, then you can `Pkg.add("COPT")` it
* To register a package
   * Install this GitHub app: https://github.com/JuliaRegistries/Registrator.jl
   * Manage the versioning with this field:
    https://github.com/COPT-Public/COPT.jl/blob/be7504e01dd5a45eb9477d00fedddc732bd5707f/Project.toml#L4
    It can get a bit confusing because COPT.jl will be a different version than COPT, the solver, but that's okay.
   * On a commit, comment `@JuliaRegistrator register`
     * Example https://github.com/jump-dev/Gurobi.jl/commit/2b6e60b8847f1990b544dd9bfcd02cea05320fe2

The first time you do this, you'll have to wait three days before it gets merged (to prevent spam). After that, registering a new version takes ~5 minutes, you just bump the version in Project.toml and call `@JuliaRegistrator register`.

**Comment by odow** [comment]
I'd setup CI before you do this though

**Comment by odow** [comment]
Want to try this now?

**Comment by COPT-Public** [comment]
I'll see if we can resolve #3 regarding Windows build, and then do this.

**Comment by odow** [comment]
Okay, let me know if you need a hand.
